import { NextRequest } from "next/server";
import { prisma } from "@/lib/db";
import { ok, created, badRequest, withErrorHandling } from "@/lib/api";
import { carbonTransactionCreateSchema } from "@/validators/environmental";
import { calculateCo2 } from "@/lib/environmental/emissions";

// GET /api/environmental/carbon-transactions
// Optional query params: ?departmentId=...&sourceType=FLEET&from=ISO&to=ISO
export async function GET(req: NextRequest) {
  return withErrorHandling(async () => {
    const { searchParams } = new URL(req.url);
    const departmentId = searchParams.get("departmentId");
    const sourceType = searchParams.get("sourceType");
    const from = searchParams.get("from");
    const to = searchParams.get("to");

    const transactions = await prisma.carbonTransaction.findMany({
      where: {
        ...(departmentId ? { departmentId } : {}),
        ...(sourceType
          ? {
              sourceType: sourceType as
                | "PURCHASE"
                | "MANUFACTURING"
                | "EXPENSE"
                | "FLEET"
                | "MANUAL",
            }
          : {}),
        ...(from || to
          ? {
              transactionDate: {
                ...(from ? { gte: new Date(from) } : {}),
                ...(to ? { lte: new Date(to) } : {}),
              },
            }
          : {}),
      },
      include: {
        department: { select: { id: true, name: true, code: true } },
        emissionFactor: { select: { id: true, name: true, unit: true } },
      },
      orderBy: { transactionDate: "desc" },
    });

    return ok(transactions);
  });
}

// POST /api/environmental/carbon-transactions
// Manual entry — co2Kg is always computed server-side, never trusted from client.
export async function POST(req: NextRequest) {
  return withErrorHandling(async () => {
    const body = await req.json();
    const parsed = carbonTransactionCreateSchema.safeParse(body);

    if (!parsed.success) {
      return badRequest("Validation failed", parsed.error.flatten());
    }

    const { departmentId, emissionFactorId, activityAmount, sourceType, sourceRef, transactionDate } =
      parsed.data;

    const department = await prisma.department.findUnique({
      where: { id: departmentId },
    });
    if (!department) return badRequest("Invalid departmentId");

    let co2Kg;
    try {
      ({ co2Kg } = await calculateCo2(emissionFactorId, activityAmount));
    } catch (err) {
      return badRequest((err as Error).message);
    }

    const transaction = await prisma.carbonTransaction.create({
      data: {
        departmentId,
        emissionFactorId,
        activityAmount,
        co2Kg,
        sourceType: sourceType ?? "MANUAL",
        sourceRef,
        transactionDate: transactionDate ? new Date(transactionDate) : undefined,
        autoGenerated: false,
      },
    });

    return created(transaction);
  });
}