// Types mirror what the Environmental API routes actually return.
// Note: Prisma Decimal fields serialize to JSON as strings, not numbers.

export type EmissionFactorStatus = "ACTIVE" | "INACTIVE";

export type CarbonSourceType =
  | "PURCHASE"
  | "MANUFACTURING"
  | "EXPENSE"
  | "FLEET"
  | "MANUAL";

export type GoalStatus =
  | "ACTIVE"
  | "ON_TRACK"
  | "AT_RISK"
  | "COMPLETED"
  | "ARCHIVED";

export interface ApiSuccess<T> {
  success: true;
  data: T;
}

export interface ApiError {
  success: false;
  error: string;
  details?: unknown;
}

export type ApiResponse<T> = ApiSuccess<T> | ApiError;

// ---------------------------------------------------------------------------

export interface DepartmentRef {
  id: string;
  name: string;
  code: string | null;
}

export interface EmissionFactor {
  id: string;
  name: string;
  category: string;
  unit: string;
  co2PerUnit: string; // Decimal
  status: EmissionFactorStatus;
  createdAt: string;
  updatedAt: string;
}

export interface ProductESGProfile {
  id: string;
  productName: string;
  productCode: string;
  category: string | null;
  carbonFootprint: string | null; // Decimal
  sustainableFlag: boolean;
  notes: string | null;
  status: EmissionFactorStatus;
  createdAt: string;
  updatedAt: string;
}

export interface CarbonTransaction {
  id: string;
  departmentId: string;
  emissionFactorId: string;
  sourceType: CarbonSourceType;
  sourceRef: string | null;
  activityAmount: string; // Decimal
  co2Kg: string; // Decimal
  transactionDate: string;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
  department?: DepartmentRef;
  emissionFactor?: { id: string; name: string; unit: string };
}

export interface EnvironmentalGoal {
  id: string;
  name: string;
  departmentId: string;
  targetCo2Kg: string; // Decimal
  currentCo2Kg: string; // Decimal
  deadline: string;
  status: GoalStatus;
  progress: number; // computed server-side, 0-100
  createdAt: string;
  updatedAt: string;
  department?: DepartmentRef;
}

export interface DepartmentSummary {
  departmentId: string;
  departmentName: string;
  departmentCode: string | null;
  totalCo2Kg: number;
  transactionCount: number;
  goalCount: number;
  environmentalScore: number | null;
}

export interface MonthlyEmissions {
  month: string; // "2026-01"
  co2Kg: number;
}

export interface SourceTypeBreakdown {
  sourceType: string;
  co2Kg: number;
  transactionCount: number;
}

export interface EnvironmentalDashboard {
  totalCo2Kg: number;
  totalTransactions: number;
  activeGoals: number;
  completedGoals: number;
  atRiskGoals: number;
  monthlyTrend: MonthlyEmissions[];
  bySourceType: SourceTypeBreakdown[];
}

// ---------------------------------------------------------------------------
// Write payloads
// ---------------------------------------------------------------------------

export interface EmissionFactorInput {
  name: string;
  category: string;
  unit: string;
  co2PerUnit: number;
  status?: EmissionFactorStatus;
}

export interface ProductESGProfileInput {
  productName: string;
  productCode: string;
  category?: string;
  carbonFootprint?: number;
  sustainableFlag?: boolean;
  notes?: string;
  status?: EmissionFactorStatus;
}

export interface CarbonTransactionInput {
  departmentId: string;
  emissionFactorId: string;
  activityAmount: number;
  sourceType?: CarbonSourceType;
  sourceRef?: string;
  transactionDate?: string;
}

export interface EnvironmentalGoalInput {
  name: string;
  departmentId: string;
  targetCo2Kg: number;
  currentCo2Kg?: number;
  deadline: string; // ISO
  status?: GoalStatus;
}