import { NextRequest } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db";
import { created, badRequest, withErrorHandling } from "@/lib/api";
import { calculateCo2 } from "@/lib/environmental/emissions";

// This endpoint simulates the "Auto Emission Calculation" business rule
// (PS Section 8): when a Purchase/Manufacturing/Expense/Fleet record is
// linked to an Emission Factor, a Carbon Transaction is generated
// automatically — no manual entry required.
//
// Since the ERP source tables (Purchase, Manufacturing, Expense, Fleet)
// aren't modeled in this service, the caller (ERP side / seed script /
// another module) passes the source record's identifying info + activity
// amount, and this endpoint does the lookup + calculation + persistence.

const autoCalculateSchema = z.object({
  departmentId: z.string().min(1, "departmentId is required"),
  emissionFactorId: z.string().min(1, "emissionFactorId is required"),
  sourceType: z.enum(["PURCHASE", "MANUFACTURING", "EXPENSE", "FLEET"]),
  sourceRef: z.string().min(1, "sourceRef is required (the originating record's ID)"),
  activityAmount: z.number().positive("activityAmount must be a positive number"),
  transactionDate: z.iso.datetime().optional(),
});

// POST /api/environmental/carbon-transactions/auto-calculate
export async function POST(req: NextRequest) {
  return withErrorHandling(async () => {
    const body = await req.json();
    const parsed = autoCalculateSchema.safeParse(body);

    if (!parsed.success) {
      return badRequest("Validation failed", parsed.error.flatten());
    }

    const { departmentId, emissionFactorId, sourceType, sourceRef, activityAmount, transactionDate } =
      parsed.data;

    const department = await prisma.department.findUnique({
      where: { id: departmentId },
    });
    if (!department) return badRequest("Invalid departmentId");

    // Guard against double-counting: if this exact source record already
    // generated a transaction, don't create a duplicate.
    const alreadyExists = await prisma.carbonTransaction.findFirst({
      where: { sourceType, sourceRef, autoGenerated: true },
    });
    if (alreadyExists) {
      return badRequest(
        `A Carbon Transaction was already auto-generated for ${sourceType} ${sourceRef}`,
        { existingTransactionId: alreadyExists.id }
      );
    }

    let co2Kg;
    try {
      ({ co2Kg } = await calculateCo2(emissionFactorId, activityAmount));
    } catch (err) {
      return badRequest((err as Error).message);
    }

    const transaction = await prisma.carbonTransaction.create({
      data: {
        departmentId,
        emissionFactorId,
        sourceType,
        sourceRef,
        activityAmount,
        co2Kg,
        transactionDate: transactionDate ? new Date(transactionDate) : undefined,
        autoGenerated: true,
      },
    });

    return created(transaction);
  });
}