import type { PrismaClient } from "@prisma/client";

/**
 * Environmental module seed data.
 * Called from prisma/seed.ts so Social/Governance/Environmental all seed
 * from one command without anyone editing each other's blocks.
 */
export async function seedEnvironmental(prisma: PrismaClient) {
  console.log("Seeding Environmental...");

  // Clean first — children before parents.
  await prisma.carbonTransaction.deleteMany();
  await prisma.environmentalGoal.deleteMany();
  await prisma.emissionFactor.deleteMany();
  await prisma.productESGProfile.deleteMany();
  await prisma.department.deleteMany();

  const [manufacturing, logistics, corporate, sales, rnd] = await Promise.all([
    prisma.department.create({ data: { name: "Manufacturing", code: "MFG" } }),
    prisma.department.create({ data: { name: "Logistics", code: "LOG" } }),
    prisma.department.create({ data: { name: "Corporate", code: "COR" } }),
    prisma.department.create({ data: { name: "Sales", code: "SAL" } }),
    prisma.department.create({ data: { name: "R&D", code: "RND" } }),
  ]);
  console.log("  departments: 5");

  const [diesel, electricity, freight, naturalGas] = await Promise.all([
    prisma.emissionFactor.create({
      data: { name: "Diesel combustion", category: "Fuel", unit: "litre", co2PerUnit: 2.68 },
    }),
    prisma.emissionFactor.create({
      data: { name: "Grid electricity (IN)", category: "Electricity", unit: "kWh", co2PerUnit: 0.71 },
    }),
    prisma.emissionFactor.create({
      data: { name: "Road freight", category: "Freight", unit: "tonne-km", co2PerUnit: 0.12 },
    }),
    prisma.emissionFactor.create({
      data: { name: "Natural gas", category: "Fuel", unit: "m3", co2PerUnit: 2.03 },
    }),
  ]);
  console.log("  emission factors: 4");

  await prisma.productESGProfile.createMany({
    data: [
      { productName: "Recycled Steel Bracket", productCode: "RSB-100", category: "Components", carbonFootprint: 4.2, sustainableFlag: true },
      { productName: "Standard Plastic Housing", productCode: "SPH-220", category: "Components", carbonFootprint: 11.8, sustainableFlag: false },
      { productName: "Bio-based Packaging", productCode: "BBP-050", category: "Packaging", carbonFootprint: 0.9, sustainableFlag: true },
      { productName: "Aluminium Frame", productCode: "ALF-330", category: "Components", carbonFootprint: 16.4, sustainableFlag: false },
    ],
  });
  console.log("  product ESG profiles: 4");

  // co2Kg computed exactly as the API computes it:
  //   co2Kg = activityAmount * emissionFactor.co2PerUnit
  await prisma.carbonTransaction.createMany({
    data: [
      { departmentId: logistics.id, emissionFactorId: diesel.id, sourceType: "FLEET", sourceRef: "FLEET-2026-0142", activityAmount: 1200, co2Kg: 1200 * 2.68, autoGenerated: true, transactionDate: new Date("2026-07-02") },
      { departmentId: logistics.id, emissionFactorId: freight.id, sourceType: "PURCHASE", sourceRef: "PO-2026-0781", activityAmount: 8400, co2Kg: 8400 * 0.12, autoGenerated: true, transactionDate: new Date("2026-07-04") },
      { departmentId: logistics.id, emissionFactorId: diesel.id, sourceType: "FLEET", sourceRef: "FLEET-2026-0155", activityAmount: 940, co2Kg: 940 * 2.68, autoGenerated: true, transactionDate: new Date("2026-07-09") },
      { departmentId: manufacturing.id, emissionFactorId: electricity.id, sourceType: "MANUFACTURING", sourceRef: "MFG-RUN-3391", activityAmount: 15600, co2Kg: 15600 * 0.71, autoGenerated: true, transactionDate: new Date("2026-07-01") },
      { departmentId: manufacturing.id, emissionFactorId: naturalGas.id, sourceType: "MANUFACTURING", sourceRef: "MFG-RUN-3392", activityAmount: 2300, co2Kg: 2300 * 2.03, autoGenerated: true, transactionDate: new Date("2026-07-06") },
      { departmentId: corporate.id, emissionFactorId: electricity.id, sourceType: "EXPENSE", sourceRef: "EXP-2026-1120", activityAmount: 4100, co2Kg: 4100 * 0.71, autoGenerated: true, transactionDate: new Date("2026-07-03") },
      { departmentId: sales.id, emissionFactorId: diesel.id, sourceType: "EXPENSE", sourceRef: "EXP-2026-1131", activityAmount: 320, co2Kg: 320 * 2.68, autoGenerated: true, transactionDate: new Date("2026-07-07") },
      { departmentId: rnd.id, emissionFactorId: electricity.id, sourceType: "MANUAL", activityAmount: 900, co2Kg: 900 * 0.71, autoGenerated: false, transactionDate: new Date("2026-07-08") },
    ],
  });
  console.log("  carbon transactions: 8");

  // Stored in kg. UI displays tonnes.
  // Ratios match the wireframe: 390/500=78%, 98/120=82%, 80/80=100%
  await prisma.environmentalGoal.createMany({
    data: [
      { name: "Reduce Fleet Emissions", departmentId: logistics.id, targetCo2Kg: 500_000, currentCo2Kg: 390_000, deadline: new Date("2026-12-31"), status: "ACTIVE" },
      { name: "Cut Packaging Waste", departmentId: manufacturing.id, targetCo2Kg: 120_000, currentCo2Kg: 98_000, deadline: new Date("2026-09-30"), status: "ON_TRACK" },
      { name: "Office Energy Cut", departmentId: corporate.id, targetCo2Kg: 80_000, currentCo2Kg: 80_000, deadline: new Date("2026-06-30"), status: "COMPLETED" },
      // Past-deadline and incomplete — exercises the AT_RISK derivation path.
      { name: "Cut R&D Lab Power", departmentId: rnd.id, targetCo2Kg: 60_000, currentCo2Kg: 25_000, deadline: new Date("2026-05-31"), status: "ACTIVE" },
    ],
  });
  console.log("  environmental goals: 4");
}