"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Plus, Zap } from "lucide-react";
import { DataTable, type Column } from "@/components/environmental/DataTable";
import { ExportButton } from "@/components/environmental/ExportButton";
import { CarbonTransactionDialog } from "@/components/environmental/carbon-transactions/CarbonTransactionDialog";
import { AutoCalculateDialog } from "@/components/environmental/carbon-transactions/AutoCalculateDialog";
import { useCarbonTransactions, useDepartmentSummaries } from "@/hooks/use-environmental";
import { formatDate, formatKg } from "@/lib/format";
import type { CsvColumn } from "@/lib/csv";
import type { CarbonTransaction } from "@/types/environmental";

const SOURCE_LABELS: Record<string, string> = {
  PURCHASE: "Purchase",
  MANUFACTURING: "Manufacturing",
  EXPENSE: "Expense",
  FLEET: "Fleet",
  MANUAL: "Manual",
};

export default function CarbonTransactionsPage() {
  const { data, isLoading, error, refetch } = useCarbonTransactions();
  const { data: departments } = useDepartmentSummaries();
  const [manualOpen, setManualOpen] = useState(false);
  const [autoOpen, setAutoOpen] = useState(false);

  const departmentOptions = (departments ?? []).map((d) => ({
    id: d.departmentId,
    name: d.departmentName,
  }));

  const columns: Column<CarbonTransaction>[] = [
    {
      key: "transactionDate",
      header: "Date",
      render: (r) => formatDate(r.transactionDate),
      sortValue: (r) => r.transactionDate,
    },
    { key: "department", header: "Department", render: (r) => r.department?.name ?? "—" },
    { key: "factor", header: "Emission Factor", render: (r) => r.emissionFactor?.name ?? "—" },
    {
      key: "sourceType",
      header: "Source",
      render: (r) => (
        <span className="text-xs text-muted">
          {SOURCE_LABELS[r.sourceType]}
          {r.autoGenerated && (
            <span className="ml-1.5 rounded-full bg-brand/10 px-1.5 py-0.5 text-brand">
              auto
            </span>
          )}
        </span>
      ),
    },
    {
      key: "sourceRef",
      header: "Source Ref",
      render: (r) => <span className="text-xs text-muted">{r.sourceRef ?? "—"}</span>,
    },
    {
      key: "activityAmount",
      header: "Activity",
      render: (r) => `${formatKg(r.activityAmount)} ${r.emissionFactor?.unit ?? ""}`,
    },
    {
      key: "co2Kg",
      header: "CO2 (kg)",
      render: (r) => <span className="font-medium">{formatKg(r.co2Kg)}</span>,
      sortValue: (r) => parseFloat(r.co2Kg),
    },
  ];

  const csvColumns: CsvColumn<CarbonTransaction>[] = [
    { header: "Date", value: (r) => r.transactionDate },
    { header: "Department", value: (r) => r.department?.name ?? "" },
    { header: "Emission Factor", value: (r) => r.emissionFactor?.name ?? "" },
    { header: "Unit", value: (r) => r.emissionFactor?.unit ?? "" },
    { header: "Source Type", value: (r) => r.sourceType },
    { header: "Source Ref", value: (r) => r.sourceRef ?? "" },
    { header: "Activity Amount", value: (r) => r.activityAmount },
    { header: "CO2 (kg)", value: (r) => r.co2Kg },
    { header: "Auto Generated", value: (r) => (r.autoGenerated ? "Yes" : "No") },
  ];

  return (
    <div className="space-y-4">
      {error && (
        <div className="rounded-lg border border-error/30 bg-error/10 px-4 py-3 text-sm text-error">
          {error}
        </div>
      )}
      <DataTable
        columns={columns}
        rows={data ?? []}
        isLoading={isLoading}
        getRowId={(r) => r.id}
        emptyLabel="No carbon transactions logged yet."
        toolbarRight={
          <div className="flex gap-2">
            <ExportButton
              rows={data ?? []}
              columns={csvColumns}
              filenameBase="carbon-transactions"
            />
            <Button
              variant="outline"
              className="border-brand/30 text-brand hover:bg-brand/10"
              onClick={() => setAutoOpen(true)}
            >
              <Zap className="mr-1.5 h-4 w-4" />
              Auto-Calculate
            </Button>
            <Button
              className="bg-brand text-white hover:bg-brand/90"
              onClick={() => setManualOpen(true)}
            >
              <Plus className="mr-1.5 h-4 w-4" />
              Log Carbon Data
            </Button>
          </div>
        }
      />

      <CarbonTransactionDialog
        open={manualOpen}
        onOpenChange={setManualOpen}
        departments={departmentOptions}
        onSaved={refetch}
      />

      <AutoCalculateDialog
        open={autoOpen}
        onOpenChange={setAutoOpen}
        departments={departmentOptions}
        onSaved={refetch}
      />
    </div>
  );
}